### ISSUE TITLE
VARK: Why is E acceptable?

### ISSUE THREAD

**Issue by criscmaia** [criscmaia/gsdslack#29]
![image](https://user-images.githubusercontent.com/9072422/32418029-541fd812-c25a-11e7-855f-8bd423f81e80.png)

**Comment by btmatthew** [comment]
You wanted to use a value of 0 as select nothing.
Value 0 is already used for purpose of selecting the previous question.
So we have agreed on using E as select nothing response.

**Comment by criscmaia** [comment]
Need to add it as an extra option for every question then.

E) none of the options above.
And if E, can't be accepted with any other value

(replying via email, not sure what happens)

**Comment by btmatthew** [comment]
We can do that but the E answer will be hidden under "show more"
![image](https://user-images.githubusercontent.com/7571876/32470296-dee17060-c34e-11e7-9cde-580889b4f8a3.png)

**Comment by criscmaia** [comment]
Not great, but better than not having it.
I assume there is no way to have it expanded by default (overall in Slack, not just for surveys), right?

**Comment by btmatthew** [comment]
text
This is the main text in a message attachment, and can contain standard message markup. The content will automatically collapse if it contains 700+ characters or 5+ linebreaks, and will display a "Show more..." link to expand the content. Links posted in the text field will not unfurl.

Screenshot of an attachment with a formatted text

You must include either the text or fallback property, otherwise the attachment will not be displayed correctly! The value of each property can be an empty string (" ").

**Comment by btmatthew** [comment]
https://api.slack.com/docs/message-attachments

**Comment by criscmaia** [comment]
Working! \o/
